#!/bin/bash

. /docker_secrets_expand.sh

set -o errexit
set -o pipefail
set -o nounset

cd zubhub

exec celery -A zubhub beat -l DEBUG &
exec celery -n zubhub -A zubhub worker -l INFO &


cd ../media
exec celery -n media -A media worker -l INFO &

tail -f /dev/null

