# Generated by Django 3.2 on 2023-07-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0010_merge_20220921_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatorGroup',
        ),
    ]
