name: Checkout files action
inputs:
  ref:
    required: false
    type: string
  repository:
    required: false
    type: string
  fetch_depth:
    required: false
    type: number
    default: 1

runs:
  using: "composite"
  steps:
    - name: Checkout files
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        repository: ${{ inputs.repository }}
        fetch-depth: ${{ inputs.fetch_depth }}
