# build environment
FROM node:16-alpine as build
WORKDIR /zubhub_frontend
ENV PATH /zubhub_frontend/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
COPY . ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /zubhub_frontend/build /usr/share/nginx/html
# new
COPY nginx/prod/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
