version: "3.3"

services:
  zubhub_frontend:
    container_name: zubhub_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure
    ports:
      - "80:80"
