version: "3.3"

services:
  zubhub_frontend:
    container_name: zubhub_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure
    ports:
      - "8080:80"

  reverse-proxy:
    image: valian/docker-nginx-auto-ssl:1.0.0
    container_name: reverse-proxy
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.ssl-data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: "(zubhub|www.zubhub).unstructured.studio"
      SITES: "zubhub.unstructured.studio=zubhub_frontend;www.zubhub.unstructured.studio=zubhub_frontend"
      FORCE_HTTPS: "true"
    depends_on:
      - zubhub_frontend

volumes:
  .ssl-data:
