version: '3.3'

services:
  zubhub_frontend:
    container_name: zubhub_frontend
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx/dev/default.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure
    ports:
      - '3000:3000'
