version: "3.3"

services:
  zubhub_frontend:
    container_name: zubhub_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure
    ports:
      - "8080:80"

  reverse-proxy:
    image: nginx:stable-alpine
    container_name: reverse-proxy
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.zero-ssl:/etc/ssl
      - ./reverse-proxy:/etc/nginx
    depends_on:
      - zubhub_frontend
