name: Backend Production Deployment

on:
  push:
    branches:
      - phase2
    paths:
      - "zubhub_backend/**"
      - "!zubhub_backend/.gitignore"
      - "!zubhub_backend/.env.example"
      - "!zubhub_backend/.dockerignore"

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout files
        uses: actions/checkout@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: zubhub_backend/
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: unstructured/zubhub-backend:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
