name: Doctl action
inputs:
  token:
    required: true
    type: string
  script:
    required: true
    type: string
outputs:
  JSON_STRING:
    value: ${{ steps.set_output.outputs.JSON_STRING }}

runs:
  using: "composite"
  steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ inputs.token }}

    - name: execute script
      id: script
      run: ${{ inputs.script }}
      shell: bash

    - name: Set output
      id: set_output
      run: echo "JSON_STRING=${{ toJson(env) }}" >> $GITHUB_OUTPUT
