# Generated by Django 3.2 on 2022-08-14 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='materials_used',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='activity',
            name='publish',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='public_id',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='inspiringexamples',
            name='credit',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
