# Generated by Django 3.2 on 2022-08-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20220814_0738'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityImages',
            new_name='ActivityImage',
        ),
        migrations.RenameModel(
            old_name='ActivityMakingSteps',
            new_name='ActivityMakingStep',
        ),
        migrations.RenameModel(
            old_name='InspiringExamples',
            new_name='InspiringExample',
        ),
    ]
