# Generated by Django 3.2 on 2022-08-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20220814_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitymakingstep',
            old_name='order',
            new_name='step_order',
        ),
    ]
