# Generated by Django 3.2 on 2022-08-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_rename_order_activitymakingstep_step_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='file_url',
        ),
    ]
