# Generated by Django 3.2 on 2022-08-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_rename_image_url_image_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='slug',
            field=models.SlugField(default='first_activity_slug', max_length=1000, unique=True),
            preserve_default=False,
        ),
    ]
