# Generated by Django 3.2 on 2022-08-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activity_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='inspiring_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspiring_artist_activities', to='activities.inspiringartist'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='materials_used_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.image'),
        ),
    ]
