# Generated by Django 3.2 on 2022-08-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20220819_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiringartist',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inspiringartist',
            name='short_biography',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
