# Generated by Django 3.2 on 2023-08-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_category'),
        ('activities', '0008_auto_20220829_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='class_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='introduction',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='category',
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='activities', to='projects.Category'),
        ),
    ]
