# Generated by Django 3.2 on 2023-08-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_auto_20230828_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitymakingstep',
            name='image',
        ),
        migrations.AddField(
            model_name='activitymakingstep',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='activities.Image'),
        ),
    ]
