# Generated by Django 3.2 on 2023-08-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_auto_20230828_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymakingstep',
            name='title',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activitymakingstep',
            name='image',
            field=models.ManyToManyField(blank=True, to='activities.Image'),
        ),
    ]
