# Generated by Django 3.2 on 2023-08-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_category'),
        ('activities', '0011_auto_20230828_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='activities', to='projects.Category'),
        ),
    ]
