# Generated by Django 3.2 on 2023-08-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_alter_activity_materials_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='materials_used',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
