# Generated by Django 3.2 on 2024-06-24 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0017_alter_activity_materials_used"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"verbose_name_plural": "Activities"},
        ),
    ]
