name: Docker build and push action
inputs:
  username:
    required: true
    type: string
  token:
    required: true
    type: string
  context:
    required: true
    type: string
  file:
    required: true
    type: string
  tags:
    required: true
    type: string
  push:
    required: true
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.tags }}

    - name: Image digest
      shell: bash
      run: echo ${{ steps.docker_build.outputs.digest }}
