# Generated by Django 3.2 on 2022-03-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20220218_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Clap'), (2, 'Comment'), (3, 'Save'), (4, 'Follow')], default=1),
            preserve_default=False,
        ),
    ]
