# Generated by Django 3.2 on 2022-03-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20220303_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
