# Generated by Django 3.2 on 2022-03-29 02:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0007_alter_notification_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='source',
        ),
        migrations.AddField(
            model_name='notification',
            name='sources',
            field=models.ManyToManyField(blank=True, null=True, related_name='notification_source', to=settings.AUTH_USER_MODEL),
        ),
    ]
