# Generated by Django 3.2 on 2022-03-29 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0008_auto_20220329_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='notification_source', to=settings.AUTH_USER_MODEL),
        ),
    ]
