version: "3.3"

services:
  web:
    container_name: web
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /start
    restart: on-failure
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - SECRET_KEY:${SECRET_KEY}
      - DEBUG:${DEBUG}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - DEFAULT_FROM_PHONE=${DEFAULT_FROM_PHONE}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_NOTIFY_SERVICE_SID=${TWILIO_NOTIFY_SERVICE_SID}
    volumes:
      - .:/zubhub_backend
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbitmq

  db:
    container_name: db
    env_file: .env
    image: postgres:11
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  rabbitmq:
    container_name: rabbitmq
    env_file: .env
    image: rabbitmq:3-management
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672

  celery_worker:
    container_name: celery_worker
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /start-celeryworker
    restart: on-failure
    volumes:
      - .:/zubhub_backend
    depends_on:
      - rabbitmq
      - db

  flower:
    container_name: flower
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5555:5555
    command: /start-flower
    restart: on-failure
    volumes:
      - .:/zubhub_backend
    depends_on:
      - celery_worker
      - rabbitmq
      - db

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: on-failure
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    restart: on-failure
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  postgres_data:
