# Generated by Django 2.2.7 on 2020-11-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
