# Generated by Django 2.2.7 on 2021-02-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_auto_20210208_0405'),
    ]

    operations = [
        
    ]
