# Generated by Django 3.2 on 2022-02-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_alter_creator_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='contact',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'WHATSAPP'), (2, 'EMAIL'), (3, 'SMS')], default=3, null=True),
        ),
    ]
