# Generated by Django 2.2.7 on 2020-11-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0003_auto_20201123_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='dateOfBirth1',
            field=models.DateField(blank=True, null=True),
        ),
    ]
