# Generated by Django 2.2.7 on 2021-03-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0004_phonenumber_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
