# Generated by Django 2.2.7 on 2020-11-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0004_creator_dateofbirth1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='dateOfBirth1',
        ),
    ]
