# Generated by Django 3.2 on 2022-03-13 06:57

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('creators', '0006_remove_creator_role_squashed_0007_alter_creator_followers'), ('creators', '0007_auto_20220308_1140')]

    dependencies = [
        ('creators', '0005_data_migrate_role_to_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='role',
        ),
        migrations.AlterField(
            model_name='creator',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creatortag',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='creatortag',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='creators_cr_search__659ff3_gin'),
        ),
    ]
