# Generated by Django 3.2 on 2022-03-05 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0005_data_migrate_role_to_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='role',
        ),
        migrations.AlterField(
            model_name='creator',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
