# Generated by Django 2.2.7 on 2021-04-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0005_auto_20210322_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'CREATOR'), (2, 'MODERATOR'), (3, 'STAFF')], default=1, null=True),
        ),
    ]
