# Generated by Django 2.2.7 on 2020-11-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0005_auto_20201123_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='creator',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='creator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
