# Generated by Django 2.2.7 on 2020-11-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0006_auto_20201124_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
