# Generated by Django 2.2.7 on 2021-04-13 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0006_creator_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'CREATOR'), (2, 'MODERATOR'), (3, 'STAFF'), (4, 'GROUP')], default=1, null=True),
        ),
        migrations.CreateModel(
            name='CreatorGroup',
            fields=[
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('projects_count', models.IntegerField(blank=True, default=0)),
                ('members', models.ManyToManyField(blank=True, related_name='creator_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
