# Generated by Django 3.1 on 2022-02-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0007_auto_20220308_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='contact',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'WHATSAPP'), (2, 'EMAIL'), (3, 'SMS'), (4, 'WEB')], default=4, null=True),
        ),
    ]
