# Generated by Django 3.2 on 2022-05-28 00:51

import creators.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0008_auto_20220222_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='contact',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(creators.models.Creator.NotificationChannel['WHATSAPP'], 'WHATSAPP'), (creators.models.Creator.NotificationChannel['EMAIL'], 'EMAIL'), (creators.models.Creator.NotificationChannel['SMS'], 'SMS'), (creators.models.Creator.NotificationChannel['WEB'], 'WEB')], default=creators.models.Creator.NotificationChannel['WEB'], null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='subscribe',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
