# Generated by Django 2.2.7 on 2020-11-29 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0008_auto_20201124_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.AddField(
            model_name='creator',
            name='location1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='creators.Location'),
        ),
    ]
