# Generated by Django 3.2 on 2022-08-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0008_auto_20220222_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='contact',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'WHATSAPP'), (2, 'EMAIL'), (3, 'SMS'), (4, 'WEB')], default=3, null=True),
        ),
    ]
