# Generated by Django 3.2 on 2022-08-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0008_auto_20220222_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Projects'), (2, 'Comments'), (3, 'Views'), (4, 'Likes')])),
                ('threshold_value', models.IntegerField(blank=True, default=0)),
                ('badge_title', models.CharField(default='', max_length=225)),
            ],
        ),
        migrations.AlterField(
            model_name='setting',
            name='contact',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'WHATSAPP'), (2, 'EMAIL'), (3, 'SMS'), (4, 'WEB')], default=3, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='creators', to='creators.Badge'),
        ),
    ]
