# Generated by Django 2.2.7 on 2020-11-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0009_auto_20201129_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(max_length=106, unique=True),
        ),
    ]
