# Generated by Django 3.2 on 2022-09-21 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0009_alter_setting_contact'),
        ('creators', '0009_auto_20220822_0842'),
    ]

    operations = [
    ]
