# Generated by Django 2.2.7 on 2020-11-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0010_auto_20201129_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
