# Generated by Django 3.2 on 2023-08-17 15:33

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0011_delete_creatorgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('groupname', models.CharField(error_messages={'unique': 'A group with that groupname already exists.'}, max_length=150, unique=True, verbose_name='groupname')),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('projects', models.JSONField(default=list)),
                ('projects_count', models.IntegerField(blank=True, default=0)),
                ('avatar', models.URLField(blank=True, max_length=1000, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('followers_count', models.IntegerField(blank=True, default=0)),
                ('badges', models.ManyToManyField(blank=True, related_name='creator_group', to='creators.Badge')),
                ('followers', models.ManyToManyField(blank=True, related_name='following_group', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='group_members', to='creators.CreatorGroup')),
                ('tags', models.ManyToManyField(blank=True, related_name='creator_group', to='creators.CreatorTag')),
            ],
        ),
        migrations.CreateModel(
            name='CreatorGroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='creators.creatorgroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='creatorgroup',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='creators_cr_search__188da8_gin'),
        ),
    ]
