# Generated by Django 2.2.7 on 2020-11-29 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0011_auto_20201129_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='location',
        ),
    ]
