# Generated by Django 2.2.7 on 2020-11-29 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0012_remove_creator_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='location1',
            new_name='location',
        ),
    ]
