# Generated by Django 2.2.7 on 2020-11-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0014_auto_20201130_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='follower',
            new_name='followers',
        ),
    ]
