# Generated by Django 2.2.7 on 2021-01-22 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0017_auto_20201210_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='following_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='creator',
            name='followers',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
