# Generated by Django 2.2.7 on 2021-02-03 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0021_auto_20210203_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='id',
        ),
        migrations.AlterField(
            model_name='setting',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
