# Generated by Django 2.2.7 on 2021-02-04 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0022_auto_20210203_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='creator',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
