# Generated by Django 2.2.7 on 2021-03-09 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0032_phonenumber_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('members', models.ManyToManyField(blank=True, related_name='creator_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
