# Generated by Django 2.2.7 on 2021-03-09 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0033_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
