# Generated by Django 2.2.7 on 2021-03-09 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0034_group_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorGroup',
            fields=[
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('members', models.ManyToManyField(blank=True, related_name='creator_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
