# Generated by Django 2.2.7 on 2021-03-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0035_auto_20210309_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorgroup',
            name='members_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
