# Generated by Django 2.2.7 on 2021-03-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0037_remove_creatorgroup_members_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorgroup',
            name='projects_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
