# Generated by Django 2.2.7 on 2021-03-10 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0038_creatorgroup_projects_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatorGroup',
        ),
    ]
