# Generated by Django 2.2.7 on 2021-03-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0040_creatorgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatorGroup',
        ),
    ]
