# Generated by Django 2.2.7 on 2021-03-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0041_delete_creatorgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'CREATOR'), (3, 'MODERATOR')], default=1, null=True),
        ),
    ]
