# Generated by Django 2.2.7 on 2021-03-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0042_creator_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'CREATOR'), (2, 'MODERATOR'), (3, 'STAFF')], default=1, null=True),
        ),
    ]
