# Generated by Django 2.2.7 on 2021-03-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0043_auto_20210319_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='role',
        ),
    ]
