# Generated by Django 2.2.7 on 2021-03-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0045_auto_20210324_0055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='creator',
            name='creators_cr_search__44165d_gin',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='search_vector',
        ),
        migrations.AddField(
            model_name='creator',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'CREATOR'), (2, 'MODERATOR'), (3, 'STAFF')], default=1, null=True),
        ),
    ]
