# Generated by Django 2.2.7 on 2021-03-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0048_creatorgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatorGroup',
        ),
    ]
