# Generated by Django 2.2.7 on 2021-03-25 15:33

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0051_auto_20210325_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={},
        ),
        migrations.AddField(
            model_name='creator',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='creator',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='creators_cr_search__44165d_gin'),
        ),
    ]
