# Generated by Django 2.2.7 on 2021-04-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0055_auto_20210413_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
