#!/bin/bash

set -o errexit
set -o nounset

cd zubhub

# worker_ready() {
#     celery -A zubhub inspect ping
# }

# until worker_ready; do
#   >&2 echo 'Celery workers not available'
#   sleep 1
# done
# >&2 echo 'Celery workers is available'

exec flower \
    --app=zubhub \
    --auto_refresh=True \
    --broker="${CELERY_BROKER}" \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"