# Generated by Django 2.2.7 on 2021-04-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zubhub', models.CharField(blank=True, max_length=50, null=True)),
                ('unstructured_studio', models.EmailField(blank=True, max_length=254, null=True)),
                ('resources', models.CharField(blank=True, max_length=50, null=True)),
                ('edited_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guidelines_and_policies', models.CharField(max_length=100)),
                ('terms_of_use', models.TextField()),
                ('edited_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
