# Generated by Django 2.2.7 on 2021-04-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.DeleteModel(
            name='FAQs',
        ),
        migrations.AlterModelOptions(
            name='help',
            options={'verbose_name': 'Help', 'verbose_name_plural': 'Help'},
        ),
        migrations.AlterModelOptions(
            name='privacy',
            options={'verbose_name': 'Privacy', 'verbose_name_plural': 'Privacy'},
        ),
    ]
