# Generated by Django 3.2 on 2022-02-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0001_squashed_0005_auto_20210920_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
