# Generated by Django 2.2.7 on 2021-06-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0001_squashed_0007_auto_20210612_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='image_project_id',
            new_name='activity_url',
        ),
    ]
