# Generated by Django 2.2.7 on 2021-09-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0001_squashed_0003_auto_20210612_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='explore_ideas_url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='footer_logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hero',
            name='footer_logo_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='hero',
            name='header_logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hero',
            name='header_logo_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
