# Generated by Django 3.2 on 2022-03-03 06:33

import django.core.validators
from django.db import migrations, models
import zubhub.utils


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0001_squashed_0005_auto_20210920_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(null=True, storage=zubhub.utils.MediaStorage(), upload_to=zubhub.utils.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['', 'jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.RenameModel(
            old_name='StaticAssets',
            new_name='AdminSettings',
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='header_logo',
            field=models.ImageField(blank=True, null=True, storage=zubhub.utils.MediaStorage(), upload_to=zubhub.utils.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['', 'jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, storage=zubhub.utils.MediaStorage(), upload_to=zubhub.utils.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['', 'jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp'])]),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='site_mode',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'PUBLIC'), (2, 'PRIVATE')], default=1),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='edited_by_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelOptions(
            name='AdminSettings',
            options={'verbose_name': 'AdminSettings', 'verbose_name_plural': 'AdminSettings'},
        ),
    ]
