# Generated by Django 2.2.7 on 2021-06-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='help',
            old_name='resources',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='privacy',
            old_name='guidelines_and_policies',
            new_name='privacy_policy',
        ),
    ]
