# Generated by Django 2.2.7 on 2021-06-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0002_auto_20210610_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('image_project_link', models.URLField(max_length=1000)),
            ],
        ),
    ]
