# Generated by Django 3.2 on 2022-03-03 06:50

from django.db import migrations


def apply(apps, schema_editor):
    """
    in Hero model, copy content of image_url to image.name for all instances.

    In AdminSettings model, copy content of header_logo_url and footer_logo_url
    to header_logo.name and footer_logo.name respectively, for all instances.
    """
    AdminSettings = apps.get_model("zubhub", "AdminSettings")
    Hero = apps.get_model("zubhub", "Hero")

    for settings in AdminSettings.objects.all():
        settings.header_logo.name = settings.header_logo_url
        settings.footer_logo.name = settings.footer_logo_url
        settings.save()

    for hero in Hero.objects.all():
        hero.image.name = hero.image_url
        hero.save()


def reverse(apps, schema_editor):
    """
    in Hero model, set image.name to None for all instances.

    In AdminSettings model, set header_logo.name and footer_logo.name to None 
    for all instances.
    """

    AdminSettings = apps.get_model("zubhub", "AdminSettings")
    Hero = apps.get_model("zubhub", "Hero")

    for settings in AdminSettings.objects.all():
        settings.header_logo.name = None
        settings.footer_logo.name = None
        settings.save()

    for hero in Hero.objects.all():
        hero.image.name = None
        hero.save()





class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0002_auto_20220213_0149_squashed_0005_auto_20220213_0927_squashed_0004_adminsettings'),
    ]

    operations = [
        migrations.RunPython(apply, reverse)
    ]
