# Generated by Django 2.2.7 on 2021-04-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0002_auto_20210406_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='published',
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='help',
            name='resources',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='help',
            name='unstructured_studio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='help',
            name='zubhub',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='guidelines_and_policies',
            field=models.TextField(),
        ),
    ]
