# Generated by Django 3.2 on 2022-03-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0003_data_sanitization'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinkeringResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tinkering Resources',
            },
        ),
    ]
