# Generated by Django 3.2 on 2022-03-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0003_data_migrate_url_to_image_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsettings',
            name='footer_logo_url',
        ),
        migrations.RemoveField(
            model_name='adminsettings',
            name='header_logo_url',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='site_mode',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PUBLIC'), (2, 'PRIVATE')], default=1),
        ),
    ]
