# Generated by Django 2.2.7 on 2021-09-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0003_auto_20210919_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.ImageField(null=True, upload_to='')),
                ('header_logo_url', models.URLField(blank=True, max_length=1000)),
                ('footer_logo', models.ImageField(null=True, upload_to='')),
                ('footer_logo_url', models.URLField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'StaticAssets',
                'verbose_name_plural': 'StaticAssets',
            },
        ),
        migrations.AddField(
            model_name='hero',
            name='explore_ideas_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
