# Generated by Django 2.2.7 on 2021-06-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0003_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='image_project_link',
        ),
        migrations.AddField(
            model_name='hero',
            name='image_project_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
