# Generated by Django 2.2.7 on 2021-04-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0003_auto_20210408_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='help',
            name='resources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='help',
            name='unstructured_studio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='help',
            name='zubhub',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='guidelines_and_policies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='terms_of_use',
            field=models.TextField(blank=True, null=True),
        ),
    ]
