# Generated by Django 3.2 on 2022-03-13 06:56

import django.core.validators
from django.db import migrations, models
import zubhub.utils


class Migration(migrations.Migration):

    replaces = [('zubhub', '0004_auto_20220303_0650'), ('zubhub', '0005_auto_20220310_0447')]

    dependencies = [
        ('zubhub', '0003_data_migrate_url_to_image_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsettings',
            name='footer_logo_url',
        ),
        migrations.RemoveField(
            model_name='adminsettings',
            name='header_logo_url',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='site_mode',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PUBLIC'), (2, 'PRIVATE')], default=1),
        ),
        migrations.AlterField(
            model_name='hero',
            name='explore_ideas_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='activity_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=zubhub.utils.MediaStorage(), upload_to=zubhub.utils.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['', 'jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp'])]),
        ),
    ]
