# Generated by Django 3.2 on 2022-03-10 04:47

import django.core.validators
from django.db import migrations, models
import zubhub.utils


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0004_auto_20220303_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='explore_ideas_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='activity_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=zubhub.utils.MediaStorage(), upload_to=zubhub.utils.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['', 'jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp'])]),
        ),
    ]
