# Generated by Django 2.2.7 on 2021-06-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0004_auto_20210611_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
