# Generated by Django 2.2.7 on 2021-09-20 01:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0004_auto_20210920_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticassets',
            name='footer_logo',
            field=models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='staticassets',
            name='header_logo',
            field=models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp'])]),
        ),
    ]
