# Generated by Django 2.2.7 on 2021-04-08 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0004_auto_20210408_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='unstructured_studio',
        ),
        migrations.RemoveField(
            model_name='help',
            name='zubhub',
        ),
    ]
