# Generated by Django 2.2.7 on 2021-06-11 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0005_auto_20210611_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'Hero', 'verbose_name_plural': 'Heroes'},
        ),
    ]
