# Generated by Django 3.2 on 2022-04-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0005_data_sanitization'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='tinkering_resource_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
