# Generated by Django 3.2 on 2022-10-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_tag_tag_name_gin_idx'),
        ('zubhub', '0006_hero_tinkering_resource_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambassadors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambassadors', models.TextField(blank=True, null=True)),
                ('edited_on', models.DateTimeField(blank=True, null=True)),
                ('projects', models.ManyToManyField(related_name='ambassador_project_picks', to='projects.Project')),
            ],
            options={
                'verbose_name': 'Ambassadors',
                'verbose_name_plural': 'Ambassadors',
            },
        ),
    ]
