# Generated by Django 3.2 on 2022-11-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_tag_tag_name_gin_idx'),
        ('zubhub', '0007_ambassadors'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadors',
            name='projects',
            field=models.ManyToManyField(related_name='ambassador_project_picks', to='projects.Project'),
        ),
    ]
