# Generated by Django 3.2 on 2022-12-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0008_ambassadors_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.TextField(blank=True, null=True)),
                ('edited_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
            },
        ),
    ]
