# Generated by Django 3.2 on 2023-10-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zubhub', '0009_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Theme_Name', models.CharField(max_length=20)),
                ('Primary_Color1', models.CharField(default='#DC3545', help_text='Enter hexcode to replace color red', max_length=16)),
                ('Primary_Color2', models.CharField(default='#FDCB00', help_text='Enter hexcode to replace color yellow', max_length=16)),
                ('Primary_Color3', models.CharField(default='#00B8C4', help_text='Enter hexcode to replace color cyan', max_length=16)),
                ('Secondary_Color1', models.CharField(default='#FFCDD2', help_text='Enter hexcode to replace color light red', max_length=16)),
                ('Secondary_Color2', models.CharField(default='#A94442', help_text='Enter hexcode to replace color dark red', max_length=16)),
                ('Secondary_Color3', models.CharField(default='#FFF7D4', help_text='Enter hexcode to replace color light yellow', max_length=16)),
                ('Secondary_Color4', models.CharField(default='#9F861E', help_text='Enter hexcode to replace color dark yellow', max_length=16)),
                ('Secondary_Color5', models.CharField(default='#E0F6F4', help_text='Enter hexcode to replace color light cyan', max_length=16)),
                ('Secondary_Color6', models.CharField(default='#03848C', help_text='Enter hexcode to replace color dark cyan', max_length=16)),
                ('Text_Color1', models.CharField(default='#212121', help_text='Enter hexcode to replace color black', max_length=16)),
                ('Text_Color2', models.CharField(default='#757474', help_text='Enter hexcode to replace color dark gray', max_length=16)),
                ('Text_Color3', models.CharField(default='#E4E4E4', help_text='Enter hexcode to replace color light gray', max_length=16)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
            },
        ),
    ]
