site_name: Zubhub-Dev-Docs

nav:
    - Installation an Environment Setup: index.md
    - Full Stack Deploy Guide: deploy.md
    - API Docs : 
               - overview.md
               - web_container.md
               - media_container.md
               - others.md  


theme: 
      name: material
      higlightjs: true
      include_homepage_in_sidebar : true
      
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
