name: Checkout files workflow
on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
      repository:
        required: false
        type: string

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
