name: Copy files workflow
on:
  workflow_call:
    inputs:
      source:
        required: true
        type: string
      target:
        required: true
        type: string

jobs:
  copy_files:
    runs-on: ubuntu-latest
    steps:
      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_BACKEND_HOST }}
          username: ${{ secrets.DO_BACKEND_USERNAME }}
          key: ${{ secrets.DO_SSHKEY }}
          source: ${{ inputs.source }}
          target: ${{ inputs.target }}
