name: Build/Deploy/Destroy Locust Service

on:
  push:
    branches:
      - master
    paths:
      - "locust/**"

  workflow_dispatch:
    inputs:
      action_type:
        description:
          "Do you want to build new locust container or deploy/destroy a locust service? type \
          'build' to build new container, 'deploy' to deploy a locust service, 'destroy' to \
          destroy existing locust service. defaults to 'build' "
        required: true
        default: "build"

jobs:
  build:
    if: ${{github.event_name == 'push' || github.event.inputs.action_type == 'build' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout files
        uses: actions/checkout@v4

      - name: Build and push locust
        id: docker_build_locust
        uses: docker/build-push-action@v5
        with:
          context: ./locust/
          file: ./locust/Dockerfile
          push: true
          tags: unstructuredstudio/zubhub-services_locust:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    if: ${{ github.event.inputs.action_type == 'deploy' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Create new droplet
        run: |
          doctl compute droplet create locust --image \
            ${{ secrets.SOURCE_SNAPSHOT_ID }} --tag-name zubhub-locust --size s-1vcpu-1gb \
            --region nyc1 --enable-monitoring --ssh-keys ${{ secrets.DO_PUBLIC_SSHKEY_FP }} --wait
          sleep 30s
          echo "NEW_DROPLET_IP=$(doctl compute droplet get locust \
            --template "{{(index .Networks.V4 1).IPAddress}}")" >> $GITHUB_ENV

      - name: Deploy locust
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ env.NEW_DROPLET_IP }}
          USERNAME: ${{ secrets.DO_BACKEND_USERNAME }}
          KEY: ${{ secrets.DO_SSHKEY }}
          script: "docker run -d -p 8089:8089 unstructuredstudio/zubhub-services_locust:latest -f /mnt/locust/locustfile.py"

  destroy:
    if: ${{ github.event.inputs.action_type == 'destroy' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Destroy Target Droplet
        run: "doctl compute droplet delete -f locust"
