# Generated by Django 3.2 on 2022-03-03 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'DRAFT'), (2, 'PREVIEW'), (3, 'AUTHENTICATED_VIEWERS'), (4, 'PUBLIC')], default=1)),
                ('publisher_id', models.CharField(blank=True, max_length=100, null=True)),
                ('visible_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='publish',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='comment_target', to='projects.publishingrule'),
        ),
        migrations.AddField(
            model_name='project',
            name='publish',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='project_target', to='projects.publishingrule'),
        ),
    ]
