# Generated by Django 2.2.7 on 2020-11-30 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20201125_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='comments_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='projects_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='likes_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_for_later', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='projects_viewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='views_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=10000)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.Project')),
            ],
        ),
    ]
