# Generated by Django 3.2 on 2022-03-06 23:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_data_published_to_publishing_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='published',
        ),
        migrations.RemoveField(
            model_name='project',
            name='published',
        ),
        migrations.RemoveField(
            model_name='publishingrule',
            name='visible_to',
        ),
        migrations.AddField(
            model_name='publishingrule',
            name='visible_to',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
