# Generated by Django 2.2.7 on 2020-11-30 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201130_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='projects_viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
