# Generated by Django 3.2 on 2022-03-14 05:30

from django.db import migrations
from lxml.html.clean import Cleaner
from lxml.html import document_fromstring


def apply(apps, schema_editor):
    """
    Sanitize Comments.
    """

    Comment = apps.get_model("projects", "Comment")
    cleaner = Cleaner()

    for comment in Comment.objects.all():
        if comment.text:
            doc = document_fromstring(comment.text)
            comment.text = cleaner.clean_html(doc).text_content()
            comment.save()



def revert(apps, schema_editor):
    pass




class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220304_0029_squashed_0005_alter_publishingrule_visible_to_squashed_0005_auto_20220306_2305'),
    ]

    operations = [
        migrations.RunPython(apply, revert),
    ]
