# Generated by Django 2.2.7 on 2021-04-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210414_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='treecomment',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
