# Generated by Django 3.2 on 2022-03-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_data_sanitization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='materials_used',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
