# Generated by Django 3.2 on 2022-12-04 15:24

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20220409_1917'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tag',
            name='tag_name_gin_idx',
        ),
    ]
