# Generated by Django 2.2.7 on 2021-04-14 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210414_0520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
