# Generated by Django 3.2 on 2022-12-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_tag_tag_name_gin_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tag',
            name='tag_name_gin_idx',
        ),
    ]
