# Generated by Django 3.2 on 2022-08-11 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('projects', '0007_tag_tag_name_gin_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='inspired_from_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspired_projects', to='activities.activity'),
        ),
    ]
