# Generated by Django 3.2 on 2022-04-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='default title', max_length=1000),
            preserve_default=False,
        ),
    ]
