# Generated by Django 2.2.7 on 2020-12-10 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20201202_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_for_future', to=settings.AUTH_USER_MODEL),
        ),
    ]
