# Generated by Django 2.2.7 on 2021-04-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_delete_comment'),
    ]

    operations = [
     migrations.RenameModel('TreeComment', 'Comment')
   ]
