# Generated by Django 3.2 on 2022-04-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20220423_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='reasons',
            field=models.ManyToManyField(blank=True, related_name='violations', to='projects.ViolationReason'),
        ),
    ]
