# Generated by Django 3.2 on 2023-08-17 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0012_auto_20230817_1533'),
        ('projects', '0008_project_inspired_from_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='group_projects', to='creators.creatorgroup'),
        ),
    ]
