# Generated by Django 2.2.7 on 2020-12-10 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20201210_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
