# Generated by Django 3.2 on 2023-07-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20230715_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(related_name='projects', to='projects.Category'),
        ),
    ]
