# Generated by Django 2.2.7 on 2020-12-10 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20201210_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
