# Generated by Django 3.2 on 2023-08-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_group'),
        ('projects', '0010_alter_project_category'),
    ]

    operations = [
    ]
