# Generated by Django 2.2.7 on 2020-12-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20201212_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
