# Generated by Django 2.2.7 on 2020-12-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20201217_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='materials_used',
            field=models.CharField(max_length=5000),
        ),
    ]
