# Generated by Django 2.2.7 on 2021-03-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_staffpick'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffPick',
        ),
    ]
