# Generated by Django 2.2.7 on 2021-03-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_comment_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='published',
        ),
    ]
