# Generated by Django 2.2.7 on 2021-03-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20210324_0055'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='projects_pr_search__1d35f9_gin',
        ),
        migrations.RemoveField(
            model_name='project',
            name='search_vector',
        ),
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
