# Generated by Django 2.2.7 on 2021-03-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_remove_comment_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
