# Generated by Django 2.2.7 on 2021-03-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_treecomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
