# Generated by Django 2.2.7 on 2021-03-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_delete_comment'),
    ]

    operations = [
        migrations.RenameModel('TreeComment', 'Comment')
    ]
