# Generated by Django 2.2.7 on 2021-04-03 18:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20210402_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='projects_ta_search__4852a3_gin'),
        ),
    ]
