# Generated by Django 2.2.7 on 2021-04-14 20:43

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20210405_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='StaffPick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('slug', models.SlugField(max_length=1000, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('projects', models.ManyToManyField(related_name='staff_picks', to='projects.Project')),
            ],
        ),
    ]
